---
apiVersion: projectriff.io/v1
kind: Invoker
metadata:
  name: python3
spec:
  version: 0.0.5-snapshot
  matchers:
  - "*.py"
  properties:
    handler:
      default: "{{ .FunctionName }}"
      description: the name of the function handler
    function:
      protocol: grpc
  files:
  - path: Dockerfile
    template: |
      FROM projectriff/python3-function-invoker:{{.InvokerVersion}}
      ARG FUNCTION_MODULE={{.ArtifactBase}}
      ARG FUNCTION_HANDLER={{.Handler}}
      ADD ./{{.ArtifactBase}} /
      {{- if .FileExists "requirements.txt" }}
      ADD ./requirements.txt /
      RUN  pip install --upgrade pip && pip install -r /requirements.txt
      {{- end }}
      ENV FUNCTION_URI file:///${FUNCTION_MODULE}?handler=${FUNCTION_HANDLER}
