# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: function.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='function.proto',
  package='function',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66unction.proto\x12\x08\x66unction\"\xb9\x01\n\x07Message\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12/\n\x07headers\x18\x02 \x03(\x0b\x32\x1e.function.Message.HeadersEntry\x1a\x1d\n\x0bHeaderValue\x12\x0e\n\x06values\x18\x01 \x03(\t\x1aM\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.function.Message.HeaderValue:\x02\x38\x01\x32\x45\n\x0fMessageFunction\x12\x32\n\x04\x43\x61ll\x12\x11.function.Message\x1a\x11.function.Message\"\x00(\x01\x30\x01\x62\x06proto3')
)




_MESSAGE_HEADERVALUE = _descriptor.Descriptor(
  name='HeaderValue',
  full_name='function.Message.HeaderValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='function.Message.HeaderValue.values', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=135,
)

_MESSAGE_HEADERSENTRY = _descriptor.Descriptor(
  name='HeadersEntry',
  full_name='function.Message.HeadersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='function.Message.HeadersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='function.Message.HeadersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=214,
)

_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='function.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='function.Message.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='headers', full_name='function.Message.headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MESSAGE_HEADERVALUE, _MESSAGE_HEADERSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=214,
)

_MESSAGE_HEADERVALUE.containing_type = _MESSAGE
_MESSAGE_HEADERSENTRY.fields_by_name['value'].message_type = _MESSAGE_HEADERVALUE
_MESSAGE_HEADERSENTRY.containing_type = _MESSAGE
_MESSAGE.fields_by_name['headers'].message_type = _MESSAGE_HEADERSENTRY
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(

  HeaderValue = _reflection.GeneratedProtocolMessageType('HeaderValue', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_HEADERVALUE,
    __module__ = 'function_pb2'
    # @@protoc_insertion_point(class_scope:function.Message.HeaderValue)
    ))
  ,

  HeadersEntry = _reflection.GeneratedProtocolMessageType('HeadersEntry', (_message.Message,), dict(
    DESCRIPTOR = _MESSAGE_HEADERSENTRY,
    __module__ = 'function_pb2'
    # @@protoc_insertion_point(class_scope:function.Message.HeadersEntry)
    ))
  ,
  DESCRIPTOR = _MESSAGE,
  __module__ = 'function_pb2'
  # @@protoc_insertion_point(class_scope:function.Message)
  ))
_sym_db.RegisterMessage(Message)
_sym_db.RegisterMessage(Message.HeaderValue)
_sym_db.RegisterMessage(Message.HeadersEntry)


_MESSAGE_HEADERSENTRY.has_options = True
_MESSAGE_HEADERSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))

_MESSAGEFUNCTION = _descriptor.ServiceDescriptor(
  name='MessageFunction',
  full_name='function.MessageFunction',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=216,
  serialized_end=285,
  methods=[
  _descriptor.MethodDescriptor(
    name='Call',
    full_name='function.MessageFunction.Call',
    index=0,
    containing_service=None,
    input_type=_MESSAGE,
    output_type=_MESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSAGEFUNCTION)

DESCRIPTOR.services_by_name['MessageFunction'] = _MESSAGEFUNCTION

# @@protoc_insertion_point(module_scope)
